# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

project_name: offat

before:
  hooks:
  - go mod tidy
  - go mod download

builds:
  - main: ./cmd/offat/
    binary: offat
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "darwin" }}macos
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE
      - README.md

sboms:
  - documents:
      - "{{ .Binary }}_{{ .Os }}_{{ .Arch }}.bom.json"
    artifacts: binary
    cmd: cyclonedx-gomod
    env:
      - GOOS={{ .Os }}
      - GOARCH={{ .Arch }}
    args: [ "app", "-main", "cmd/offat", "-licenses", "-packages", "-json", "-output", "$document", "../" ]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

brews:
  - name: amass
    repository:
      owner: dmdhrumilmistry
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/OWASP/OFFAT/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: dmdhrumilmistry
      email: dmdhrumilmistry@users.noreply.github.com
    folder: Formula
    homepage: "https://owasp.org/OFFAT/"
    description: "Autonomous REST API Vulnerability Assessment Tool"
    test: |
      system "#{bin}/offat -v"
    install: |
      bin.install "offat"