name: "Build and Push Dev/main OWASP OFFAT Docker Images to DockerHub"

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build-and-push-main-docker-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and publish version tag image
      - name: Build and push offat-base docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/
          file: ./src/DockerFile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/offat:${{ github.head_ref || github.ref_name }} # for release: ${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          sbom: true
      